### ISSUE TITLE
HTML ID and Class Name Best Practices

### ISSUE THREAD

**Issue by jordanwillis** [gustavohmc/colmar#1]
Overall you HTML looks really good and you did a nice job using indentation and styling rules (which greatly increased your code readability)!  In addition to following these format/style related best practices, I would like to recommend that you follow element ID and class name best practices as well.

1. Format/Style

- One best practice related to format/style is to always stick with lower case ID and class names.  The reason for this is because HTML is case sensitive but CSS is NOT case sensitive, and this disparity can cause some unexpected behaviors.  So instead of an ID name like `mobileHeader`, I would use `mobile-header` instead.

- The above example leads into the other format/style related because practice, which is to use dashes instead of underscores (snake case) for ID and class names.  This is just one of those broadly adopted best practices that might be tied to some logical rational, but I have no idea what it is (kind of like why 2 space indentation instead of 4).

2. Semantics

The final best practice is related to the actual names themselves.  It is better to shy away from presentational and style related names and use names that reflect the purpose of the element in question.  So for example, instead of something like `intro_column_left` (which is presentational because the name describes the layout) you could use something like `main-content`.  The overall point is to use ID and class names to give context to what is actually contained in the element and not how it looks or is laid out.

Checkout the Google HTML/CSS style guide for other important best practices.

google.github.io/styleguide/htmlcssguide.html

**Comment by gustavohmc** [comment]
Thanks for the feedback. It's good to know best practices, it will help when I start working on projects or apply for a job. I like how this review helps add knowledge that wasn't covered during the course
