### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [gustavohmc/colmar#2]
You did an outstanding job creating well structured and DRY (don't repeat yourself) CSS!  I was impressed that you recognized that several properties would end up being repeated, so you structured your selectors accordingly by using combination rules such as this.

```
.orientation_img,
.campus_img,
.lecture_img{
  width: 35%;
  height: auto;
}

.orientation_txt,
.campus_txt,
.lecture_txt{
  width: 65%;
  text-align: center;
  opacity: 0.7;
}
```

Assuming you have already read my HTML ID and class name feedback, following those best practices actually results in simpler CSS.  As an example of this, I would probably collapse these class names (which are not really presentation related but rather too specific and unable to be re-used), to class names that describe the common purpose of each section.  Here is an example of what I mean.

```
.media-container {
  width: 35%;
  height: auto;
}

.text-content {
  width: 65%;
  text-align: center;
  opacity: 0.7;
}
```

Now we have semantic names that describe the purpose of the elements that we can re-use throughout the document resulting in simplified CSS.

**Comment by gustavohmc** [comment]
Makes total sense. I'll start checking for those when I'm designing the project before starting coding
