### ISSUE TITLE
Summary: Grade = Exceeds Expectations

### ISSUE THREAD

**Issue by jordanwillis** [gustavohmc/colmar#4]
Overall you did a fantastic job on this project!  You demonstrated your ability to implement a responsive design based upon project specifications, and even added some nice extra styling flare.  I also liked that you demonstrated your comfort with both flexbox and grid, which will pay huge dividends for the future.

You definitely hit it out of the park with all the basic things, so hopefully my recommendations on naming and layouts helps further mature your web development understanding.

Keep up the great work!

**Comment by gustavohmc** [comment]
I'm very happy with the result! Great to see I'm improving and becoming more comfortable with HTML and CSS. I'll definitely follow your suggestions on my next project!
